#!/bin/sh
#
# Test pre-commit hook to compile w. typescript
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
export SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
export BASEDIR=`pwd`
# Redirect output to stderr.
exec 1>&2
echo "The script dir: [$SCRIPT_DIR]; called from: [$BASEDIR]"
npm run build
STAT=$?
git add ./dist
echo "Exit status of tsc was: [$STAT]"
exit $?